                Table               users             {
_id          ObjectId      [    primary  key ]
    firstName    string         [   not null            ]
lastName            string      [   not                         null]
    }